[mapbox]

# Configure Streamlit to use a custom Mapbox token for elements like st.deck_gl_chart and st.map. To get a token for yourself, create an account at https://mapbox.com. It's free (for moderate usage levels)!
# Default: ""
token = "sk.eyJ1IjoiamVzd2JzIiwiYSI6ImNscGswZzJsMTA1YnYyanF2Y2liNDZ0bjgifQ.rgJ4q6jeVsotKmyGXxabdQ"
